### ISSUE TITLE
Issues running CountTagRNATagSeqFastQ.py

### ISSUE THREAD

**Issue by thessyed** [ewallace/pyRNATagSeq#1]
Hi Dr. Wallace,

Really appreciate this package as a quick method to split RNAtag-seq reads! I am running into some issues with the CountTagRNATagSeqFastQ.py script that I'm thinking may have to do with version differences for python but am interested in what you think. I am using python 3.9.1. for reference and running the example data.

Specifically, when I attempt to run the example code:

`python CountTagRNATagSeqFastQ.py -o Sample_4reads_TagCounts.txt data/Sample_4reads_R1.fastq.gz`

I receive the following error:

`File "/dataone/syedsa2/220114_RNAseqTestSaad/pyRNATagSeq/CountTagRNATagSeqFastQ.py", line 37
    print "Counting TagReads for file:\n" + options.fastq_fn
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Counting TagReads for file:\n" + options.fastq_fn)?`

This error goes through most of the python script where the print command is used (i.e. lines 65, 78, 87)

As well, I get errors for spaces/tab inconsistencies in several lines (i.e. line 40). 

I was able to address these issues by just modifying the script to address the syntax concerns but am now running into the following error which I am unable to address and would appreciate any help with!

`Traceback (most recent call last):
  File "/dataone/syedsa2/220114_RNAseqTestSaad/pyRNATagSeq/CountTagRNATagSeqFastQ.py", line 82, in <module>
    writer.writerow( ["TagRead","Count"] )
TypeError: a bytes-like object is required, not 'str' `

Please let me know if anything is unclear or if you need any further information from me. 

Kind regards,
Saad

**Comment by ewallace** [comment]
Hello and thanks for using this! I'm glad you found it useful. Actually this code is no longer under active development, it is probably legacy.

Yes, I think you are right that this is a python version as I wrote `CountTagRNATagSeqFastQ.py` in python 2 some years ago.

I have a few suggestions.

1. Use [conda](https://docs.conda.io/en/latest/) to create a python 2.x environment and see if you can run this script there.
2. Try the successor tool that we wrote in the riboviz package, 
[riboviz.tools.demultiplex_fastq](https://github.com/riboviz/riboviz/blob/main/riboviz/demultiplex_fastq.py), briefly explained at https://github.com/riboviz/riboviz/blob/main/docs/user/command-line-tools.md)
3. I think the functionality you need should be available in the more recent and very nice [UMItools package](https://umi-tools.readthedocs.io/en/latest/QUICK_START.html)

I hope one of these helps!

**Comment by thessyed** [comment]
This is very helpful, thanks so much!! I will move on to the successor tool or UMItools!
